version: "3"

services:
  todofront:
    build: ./todo-app/front-end/
    restart: always
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    networks:
      - todo-app

  todoback:
    build: ./todo-app/back-end/
    restart: always
    ports:
      - 3001:3001
    networks:
      - todo-app

  todotests:
    build: ./todo-app/tests/
    restart: always
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
    networks:
      - todo-app

networks:
  todo-app: